# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_add_padel_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('PADEL', 'PADEL'), ('TOUCH', 'TOUCH')], default='TOUCH', max_length=10),
        ),
    ]
