# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_tournament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tournaments_played',
            field=models.ManyToManyField(blank=True, to='player.Tournament'),
        ),
    ]
